# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Indiviual"
license = "MIT"
licenselink = "https://github.com/daniel-z-johnson/indiviual/blob/master/LICENSE"
description = "A simple theme for Hugo"
homepage = "https://github.com/daniel-z-johnson/indiviual"
tags = ["home", "blog", "tags", "simple"]
features = ["home", "blog", "tags", "simple"]
min_version = "0.60"

[author]
  name = "Daniel Z Johnson"
  homepage = ""
